name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ doxygen graphviz

    - name: Configure and Build
      run: |
        cmake -B build
        cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate Documentation
      run: |
        doxygen Doxyfile

    - name: Verify Documentation
      run: |
        if [ -f "html/index.html" ]; then
          ls -la html/index.html
          echo "Documentation generated successfully in html/"
        else
          echo "Documentation generated but path may differ"
          find . -name "index.html" -type f 2>/dev/null | head -3
        fi
